### ISSUE TITLE
[Bug]:  startup slowing

### ISSUE THREAD

**Issue by hayden-fr** [hayden-fr/ComfyUI-Model-Manager#71]
Slow startup, possibly caused by scanning.

**Comment by hayden-fr** [comment]
Is ComfyUI starting slowly or is it taking too long to load when opening the page in the browser?

When ComfyUI starts, the extension does not have any scanning behavior, but there will be a version check. Compare the versions in `pyproject.toml` and `web/version.yaml`. If they are inconsistent, download the corresponding web dist from release. The download process may take some time.

When opened in a browser, a list of models is requested. For users with a large number of models, this may be the main reason why startup feels slow.

More information needs to be collected to confirm.

**Comment by Ainaemaet** [comment]
Same version in both pyproject.toml and web/version.yaml. 

ComfyUI starts as quickly as it should (well, as quick as ever with my setup - I have an extensive list of custom_nodes that definitely slow down the startup time, but that is unrelated to the mod and running as expected). 

The issue is only when opening the page in the browser, and confirmed to be this mod - as removing it stops the problem and it only started after installing it. 

It is almost certain to be related to how many models I have (many hundreds) - though as mentioned previously this is the only model manager that takes that long. 

In fact, most are near-immediate and have a negligible effect on startup speed, aside from the Lora Sidebar custom_node I linked in previous thread; which takes about 45 seconds or so, but still much quicker than this one. 

Just let me know if there is anything else I can gather or do to help and I'm happy to assist however I am able. 


Also, thanks for creating the new issues for these. Should there be anything else, I will be sure to create a new one for each request going forwards!
